# Generated by Django 5.0 on 2024-01-23 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices_details',
            fields=[
                ('devices_id', models.AutoField(primary_key=True, serialize=False)),
                ('Device_name', models.CharField(max_length=255)),
                ('Device_Details', models.CharField(max_length=255)),
                ('Device_status', models.IntegerField()),
            ],
            options={
                'db_table': 'Devices_details',
            },
        ),
        migrations.CreateModel(
            name='Data_store',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('values', models.IntegerField()),
                ('DateTime', models.DateTimeField(auto_now_add=True)),
                ('devices', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Data_store', to='Station.devices_details')),
            ],
            options={
                'db_table': 'Data_store',
            },
        ),
    ]
