# Generated by Django 5.0 on 2024-01-23 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_store',
            old_name='values',
            new_name='device_values',
        ),
        migrations.AlterField(
            model_name='data_store',
            name='devices',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='data_store',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
