# Generated by Django 5.0 on 2024-02-28 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Station', '0002_rename_values_data_store_device_values_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data_store',
            old_name='DateTime',
            new_name='date_time',
        ),
        migrations.RenameField(
            model_name='data_store',
            old_name='devices',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='devices_details',
            old_name='Device_Details',
            new_name='device_details',
        ),
        migrations.RenameField(
            model_name='devices_details',
            old_name='devices_id',
            new_name='device_id',
        ),
        migrations.RenameField(
            model_name='devices_details',
            old_name='Device_name',
            new_name='device_name',
        ),
        migrations.RenameField(
            model_name='devices_details',
            old_name='Device_status',
            new_name='device_status',
        ),
    ]
